### ISSUE TITLE
Test Live Mode from Pickup Protocol

### ISSUE THREAD

**Issue by FabioPinheiro** [input-output-hk/didcomm-v2-mediator-test-suite#16]
### Proposed protocol

[Pickup Protocol Live Mode Change](https://didcomm.org/messagepickup/3.0/)

Test for https://github.com/input-output-hk/atala-prism-mediator/issues/145

### Scenario name

Test Pickup Protocol Live Mode Change

### Scenario BDD description

Via HTTP:
- Send a Live Mode Change
- MUST get a problem report

Via WS:
- Send a Live Mode Change
- MUST get a Status
- MUST get a Message Delivery for each forward message send via the mediator

**Comment by mineme0110** [comment]
Closing fixed in this [pr](https://github.com/input-output-hk/didcomm-v2-mediator-test-suite/pull/20 )
